				/***************/
                /* CREATE USER */
                /***************/

Create User C##Server3773 Identified By uqac123456;
Grant Create Session to C##Server3773;
GRANT UNLIMITED TABLESPACE TO C##Server3773;


                /***************/
                /* DROP TABLES */
                /***************/

Drop Table C##Server3773.LienFilmPersonnelTechnique;  
Drop Table C##Server3773.PersonnelTechnique;
Drop Table C##Server3773.RoleTechnique;
Drop Table C##Server3773.LienFilmPersonnage;
Drop Table C##Server3773.Personnage;
Drop Table C##Server3773.Acteur;
Drop Table C##Server3773.LienFilmPays;
Drop Table C##Server3773.Pays;
Drop Table C##Server3773.LienFilmGenre;
Drop Table C##Server3773.Genre;
    Drop Table C##Server3773.Location;
Drop Table C##Server3773.Examplaire;
     Drop Table C##Server3773.Film;
Drop Table C##Server3773.Langue;
     Drop Table C##Server3773.Client;
Drop Table C##Server3773.CarteDeCredit;
Drop Table C##Server3773.TypeCarteDeCredit;
Drop Table C##Server3773.Forfait;
    Drop Table C##Server3773.Employe;
Drop Table C##Server3773.Addresse;

                
                /***********************/
                /* CREATION DES TABLES */
                /* - Addresse          */
                /*      - Employe      */
                /* - Forfait           */
                /* - TypeCarte         */
                /* - CarteDeCredit     */
                /*      - Client       */
                /* - Langue            */
                /*      - Film         */
                /* - Examplaire        */
                /*      - Location     */
                /* - Genre             */
                /* - LienGenre         */
                /* - Pays              */
                /* - LienPays          */
                /* - Acteur            */
                /* - Personnage        */
                /* - LienPersonnage    */
                /* - Role              */
                /* - Personnel         */
                /* - LienPersonnel     */
                /***********************/

-- (Composante de Employe et Client) Addresse    
create Table C##Server3773.Addresse(
    IDAddresse          Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NumeroCivic         Number                  Not Null,
    Rue                 varchar2(30 CHAR)       Not Null,
    Ville               varchar2(20 CHAR)       Not Null,
    Province            varchar2(20 CHAR)        Not Null,
    CodePostal          varchar2(6 CHAR)        Not Null,
    
    Primary Key (IDAddresse),
    Unique(NumeroCivic, Rue, Ville, Province, CodePostal),
    
    Constraint Addresse_ID Check (IDAddresse > 0),
    Constraint Addresse_Numero Check (NumeroCivic > 0),
    Constraint Addresse_Rue Check( Regexp_Like (Rue, '[a-zA-Z]{3,}')),
    Constraint Addresse_Ville Check( Regexp_Like (Ville, '[a-zA-Z]{3,}')),
    Constraint Addresse_Province Check( Regexp_Like (Province, '[a-zA-Z]{3,}')),
    Constraint Addresse_CodePostal Check( Regexp_Like (CodePostal, '[a-zA-Z][0-9][a-zA-Z]\s*[0-9][a-zA-Z][0-9]'))
    );        

 -- (Table Principale) Employe  ************************************************   
create Table C##Server3773.Employe(
    Matricule           varchar2(8 CHAR)        Not Null,
    Email               varchar2(100 CHAR)      Not Null,
    MotDePasse          varchar2(22 CHAR)       Not Null,
    Prenom              varchar2(20 CHAR)       Not Null,
    Nom                 varchar2(20 CHAR)       Not Null,
    DateDeNaissance     Date                    Not Null,
    Telephone           Number                  Not Null,
    Addresse            Number                  Not Null, 
    
    Primary Key (Matricule),
    Unique (Email),
    Foreign Key (Addresse) References C##Server3773.Addresse(IDAddresse),
    
    Constraint Employe_Matricule Check( Regexp_Like (Matricule, '[A-Z0-9]{8}')),
    Constraint Employe_Email Check( Regexp_Like (Email, '\w+@\w+(\.\w+)+')),
    Constraint Employe_MotDePasse Check( Regexp_Like (MotDePasse, '^[a-zA-Z][a-zA-Z0-9]{7,}$')),
    Constraint Employe_Prenom Check( Regexp_Like (Prenom, '[a-zA-Z]{1,}')),
    Constraint Employe_Nom Check( Regexp_Like (Nom, '[a-zA-Z]{1,}')),
    Constraint Employe_DateDeNaissance Check (Extract (Year From DateDeNaissance) > 1850),
    Constraint Employe_Telephone Check (Telephone > 999999999 AND Telephone < 10000000000)
    );

-- (Composante De Client) Forfait    
create Table C##Server3773.Forfait(
    IDForfait           Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nom                 varchar2(20 CHAR)       Not Null,
    Cout                number                  Not Null,
    MaxLocation         number                  Not Null,
    MaxDuree            number                  Not Null,
    
    Primary Key (IDForfait),
    Unique(Nom, Cout, MaxLocation, MaxDuree),
    
    Constraint Forfait_ID Check (IDForfait > 0),
    Constraint Forfait_Cout Check( cout > 0 and Cout < 101),
    Constraint Forfait_MaxLocation Check( MaxLocation > 0 and MaxLocation < 100),
    Constraint Forfait_MaxDuree Check( MaxDuree > 0)
    );    

-- (Composante de Carte De Credit) Type de Carte De Credit
create Table C##Server3773.TypeCarteDeCredit (
    IDType              Number                  Not Null,
    NomType             varchar2(20 CHAR)       Not Null,
    
    Primary Key (IDType),
    Unique (NomType),
    
    Constraint TypeCarte_ID Check (IDType > 0),
    Constraint TypeCarte_Nom Check( Regexp_Like (NomType, '[a-zA-Z]{3,}'))
    );

-- (Composante de Client) Carte De Credit
create Table C##Server3773.CarteDeCredit(
    IDCarteDeCredit     Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Numero              varchar2(19 CHAR)       Not Null,
    DateExpiration      Date                    Not Null,
    CVC                 varchar2(4 CHAR)        Not Null,
    TypeCarte           Number                  Not Null,
    
    Primary Key (IDCarteDeCredit),
    Unique(Numero, DateExpiration, CVC, TypeCarte),
    Foreign Key (TypeCarte) References C##Server3773.TypeCarteDeCredit(IDType),
    
    Constraint CarteDeCredit_ID Check (IDCarteDeCredit > 0),
    Constraint CarteDeCredit_Numero Check( Regexp_Like (Numero, '\d{8,19}')),
    Constraint CarteDeCredit_CVC Check( Regexp_Like (CVC, '\d{3,4}'))
    );

-- (Table Principale) Client    ************************************************
create Table C##Server3773.Client(
    IDClient            Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Email               varchar2(100 CHAR)      Not Null,
    MotDePasse          varchar2(22 CHAR)       Not Null,
    Prenom              varchar2(20 CHAR)       Not Null,
    Nom                 varchar2(20 CHAR)       Not Null,
    DateDeNaissance     Date                    Not Null,
    Telephone           Number                  Not Null,
    Addresse            Number                  Not Null,
    Forfait             Number                  Not Null,
    CarteDeCredit       Number                  Not Null,
    
    
    Primary Key (IDClient),
    Unique (Email),
    Foreign Key (Addresse) References C##Server3773.Addresse(IDAddresse),
    Foreign Key (Forfait) References C##Server3773.Forfait(IDForfait),
    Foreign Key (CarteDeCredit) References C##Server3773.CarteDeCredit(IDCarteDeCredit),
    
    Constraint Client_ID Check (IDClient > 0),
    Constraint Client_Email Check( Regexp_Like (Email, '\w+@\w+(\.\w+)+')),
    Constraint Client_MotDePasse Check( Regexp_Like (MotDePasse, '^[a-zA-Z][a-zA-Z0-9]{5,}$')),
    Constraint Client_Prenom Check( Regexp_Like (Prenom, '[a-zA-Z]{1,}')),
    Constraint Client_Nom Check( Regexp_Like (Nom, '[a-zA-Z]{1,}')),
    Constraint Client_DateDeNaissance Check (Extract (Year From DateDeNaissance) > 1850),
    Constraint Client_Telephone Check (Telephone > 999999999 AND Telephone < 10000000000)
    );

-- (Composant De Film) Langue    
create Table C##Server3773.Langue(
    IDLangue            Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NomLangue           varchar2(15 CHAR)       Not Null,
    
    Primary Key (IDLangue),
    Unique (NomLangue),
    
    Constraint Lanuge_ID Check (IDLangue > 0),
    Constraint Langue_Nom Check( Regexp_Like (NomLangue, '[a-zA-Z]{3,}')) /*Les languages les plus court sont Ido, Ewe, Laz, Twi*/
    );
 
-- (Table Principale) Film  ****************************************************
create Table C##Server3773.Film(
    IDFilm              Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Titre               varchar2(40 CHAR)       Not Null,
    AnneeDeSortie       Number                  Not Null,
    Resume              Clob,
    Duree               Number,
    Langue              Number,
    
    Primary Key (IDFilm),
    Foreign Key (Langue) References C##Server3773.Langue(IDLangue),
    Unique (Titre,AnneeDeSortie),
    
    Constraint Film_ID Check (IDFilm > 0),
    Constraint Film_Titre Check( Regexp_Like (Titre, '[a-zA-Z]{3,}')),
    Constraint Film_Duree Check (Duree Is Null Or Duree > 0 and Duree < 51421), /*Plus long film jamais tournee: Logistics, 35 Jours, 17 heures (51420 Minutes)*/
    Constraint Film_Annee Check (AnneeDeSortie > 1887) /*Premier film jamais tournee: Roundhay Garden Scene, 1888*/
    );

-- (Composante de Location) Examplaire 
create Table C##Server3773.Examplaire(
    IDExamplaire        Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    IDFilm              Number                  Not Null,
    
    Primary Key (IDExamplaire),
    Foreign Key (IDFilm) References C##Server3773.Film(IDFilm),
    
    Constraint Examplaire_ID Check (IDExamplaire > 0)
    );

-- (Table Principale) Location  ************************************************    
create Table C##Server3773.Location(
    IDLocation          Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DateLocation        Date                    Not Null,
    DateRetour          Date                    Not Null,
    ConfirmationRetour  Date,
    Examplaire          Number                  Not Null,
    Client              Number                  Not Null,
    
    Primary Key (IDLocation),
    Unique(DateLocation, DateRetour, Examplaire),
    Foreign Key (Examplaire) References C##Server3773.Examplaire(IDExamplaire),
    Foreign Key (Client) References C##Server3773.Client(IDClient),
    
    Constraint Location_ID Check (IDLocation > 0)
    );

-- (Lié à Film) Genre                                                   ********      
create Table C##Server3773.Genre(
    IDGenre             Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NomGenre            varchar2(15 CHAR)       Not Null,
    
    Primary Key (IDGenre),
    Unique (NomGenre),
    
    Constraint Genre_ID Check (IDGenre > 0),
    Constraint Genre_Nom Check( Regexp_Like (NomGenre, '[a-zA-Z]{2,}')) 
    );

-- (Table De Lien) Genre -> Film     
create Table C##Server3773.LienFilmGenre(
    FilmID                Number                  Not Null,
    GenreID               Number                  Not Null,
    
    Primary Key (FilmID, GenreID),
    Foreign Key (FilmID) References C##Server3773.Film(IDFilm),
    Foreign Key (GenreID) References C##Server3773.Genre(IDGenre)
    );

-- (Lié à Film) Pays                                                    ********
create Table C##Server3773.Pays(
    IDPays             Number                   GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NomPays            varchar2(15 CHAR)        Not Null,
    
    Primary Key (IDPays),
    Unique (NomPays),
    
    Constraint Pays_ID Check (IDPays > 0),
    Constraint Pays_Nom Check( Regexp_Like (NomPays, '[a-zA-Z]{4,}')) /*Les pays ayant les nom les plus court sont Cuba, Irak, Iran, Mali, Niue, Oman, Togo*/
    );    
 
-- (Table De Lien) Pays -> Film 
create Table C##Server3773.LienFilmPays(
    FilmID                Number                  Not Null,
    PaysID                Number                  Not Null,
    
    Primary Key (FilmID, PaysID),
    Foreign Key (FilmID) References C##Server3773.Film(IDFilm),
    Foreign Key (PaysID) References C##Server3773.Pays(IDPays)
    );
    
-- (Composant De Personnage) Acteur        
create Table C##Server3773.Acteur(
    IDActeur            Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Prenom              varchar2(20 CHAR)       Not Null,
    Nom                 varchar2(20 CHAR)       Not Null,
    DateDeNaissance     Date,
    LieuDeNaissance     varchar2(20 CHAR),
    Biographie          Clob,
    
    Primary Key (IDActeur),
    
    Constraint Acteur_ID Check (IDActeur > 0),
    Constraint Acteur_Prenom Check( Regexp_Like (Prenom, '[a-zA-Z]{1,}')),
    Constraint Acteur_Nom Check( Regexp_Like (Nom, '[a-zA-Z]{1,}')),
    Constraint Acteur_DateDeNaissance Check (DateDeNaissance Is Null Or Extract (Year From DateDeNaissance) > 1850),
    Constraint Acteur_LieuDeNaissance Check( Regexp_Like (LieuDeNaissance, '[a-zA-Z]|[a-zA-Z],[a-zA-Z]'))
    );

-- (Lié à Film) Personnage                                              ********  
create Table C##Server3773.Personnage(
    IDPersonnage        Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Prenom              varchar2(20 CHAR)       Not Null,
    Nom                 varchar2(20 CHAR),
    DateDeNaissance     Date,
    Acteur              Number                  Not Null,
    
    Primary Key (IDPersonnage),
    Foreign Key (Acteur) References C##Server3773.Acteur(IDActeur),
    
    Constraint Personnage_ID Check (IDPersonnage > 0),
    Constraint Personnage_Prenom Check( Regexp_Like (Prenom, '[a-zA-Z]{1,}')),
    Constraint Personnage_Nom Check( Regexp_Like (Nom, '[a-zA-Z]{1,}')),
    Constraint Personnage_DateDeNaissance Check (DateDeNaissance Is Null Or Extract (Year From DateDeNaissance) > 1850)
    );

-- (Table De Lien) Personnage -> Film     
create Table C##Server3773.LienFilmPersonnage(
    FilmID                Number                  Not Null,
    PersonnageID          Number                  Not Null,
    
    Primary Key (FilmID, PersonnageID),
    Foreign Key (FilmID) References C##Server3773.Film(IDFilm),
    Foreign Key (PersonnageID) References C##Server3773.Personnage(IDPersonnage)
    );
    
-- (Composant De Personnel Technique) Role Technique [SCENARISTE, REALISATEUR...] 
create Table C##Server3773.RoleTechnique(
    IDRole              Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NomRole             varchar2(20 CHAR)       Not Null,
    
    Primary Key (IDRole),
    Unique (NomRole),
    
    Constraint Role_ID Check (IDRole > 0),
    Constraint Role_Nom Check( Regexp_Like (NomRole, '[a-zA-Z]{3,}')) 
    );

-- (Lié à Film) Personnel Technique                                     ******** 
create Table C##Server3773.PersonnelTechnique(
    IDPersonnel         Number                  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Prenom              varchar2(20 CHAR)       Not Null,
    Nom                 varchar2(20 CHAR),
    DateDeNaissance     Date,
    Role                Number                  Not Null,
    
    Primary Key (IdPersonnel),
    Foreign Key (Role) References C##Server3773.RoleTechnique(IDRole),
    
    Constraint Personnel_ID Check (IDPersonnel > 0),
    Constraint Personnel_Prenom Check( Regexp_Like (Prenom, '[a-zA-Z]{1,}')),
    Constraint Personnel_Nom Check( Regexp_Like (Nom, '[a-zA-Z]{1,}')),
    Constraint Personnel_DateDeNaissance Check (DateDeNaissance Is Null Or Extract (Year From DateDeNaissance) > 1850)
    );

        
-- (Table De Lien) Personnel Technique -> Film    
create Table C##Server3773.LienFilmPersonnelTechnique(
    FilmID                Number                  Not Null,
    PersonnelID           Number                  Not Null,
    
    Primary Key (FilmID, PersonnelID),
    Foreign Key (FilmID) References C##Server3773.Film(IDFilm),
    Foreign Key (PersonnelID) References C##Server3773.PersonnelTechnique(IDPersonnel)
    );
	
	           
            /********************************/
            /* INSERER DONNEES MANUELLEMENT */
            /********************************/

Insert Into C##Server3773.Addresse values(Null, 100, 'AddR1', 'AddV1','AddP1','A1D1D1');
Insert Into C##Server3773.Addresse values(Null, 200, 'AddR2', 'AddV2','AddP2','A2D2D2');
Insert Into C##Server3773.Addresse values(Null, 300, 'AddR3', 'AddV3','AddP3','A3D3D3');

Insert Into C##Server3773.Employe values ('EMP12341', 'emp1@domain.com', 'Emp12345','EmpP1', 'EmpN1', To_Date('1990/1/1'), To_Number('1234567891'),1);
Insert Into C##Server3773.Employe values ('EMP12342', 'emp2@domain.com', 'Emp12345','EmpP2', 'EmpN2', To_Date('1990/2/1'), To_Number('1234567891'),2);
Insert Into C##Server3773.Employe values ('EMP12343', 'emp3@domain.com', 'Emp12345','EmpP3', 'EmpN3', To_Date('1990/3/1'), To_Number('1234567891'),3);
Insert Into C##Server3773.Employe values ('EMP12344', 'emp4@domain.com', 'Emp12345','EmpP4', 'EmpN4', To_Date('1990/4/1'), To_Number('1234567891'),2);
Insert Into C##Server3773.Employe values ('EMP12345', 'emp5@domain.com', 'Emp12345','EmpP5', 'EmpN5', To_Date('1990/5/1'), To_Number('1234567891'),1);

Insert Into C##Server3773.TypeCarteDeCredit values (3, 'American Express');
Insert Into C##Server3773.TypeCarteDeCredit values (4, 'Visa');
Insert Into C##Server3773.TypeCarteDeCredit values (5, 'MasterCard');
Insert Into C##Server3773.TypeCarteDeCredit values (6, 'Discover');

Insert Into C##Server3773.CarteDeCredit values (Null, '300000000012',To_Date('2022/3/1'),'323',3);
Insert Into C##Server3773.CarteDeCredit values (Null, '4222222222222',To_Date('2022/4/1'),'423',3);
Insert Into C##Server3773.CarteDeCredit values (Null, '523456789008',To_Date('2022/5/1'),'523',3);
Insert Into C##Server3773.CarteDeCredit values (Null, '6011111111111117',To_Date('2022/6/1'),'623',3);

Insert Into C##Server3773.Forfait values (Null,'Debutant',10,1,7);
Insert Into C##Server3773.Forfait values (Null,'Intermediaire',20,5,14);
Insert Into C##Server3773.Forfait values (Null,'Avance',30,10,999);
    
Insert Into C##Server3773.Client values (Null, 'client1@domain.com', 'Client1231', 'ClientP1', 'ClientN1', To_Date('1990/1/1'), '1234567890',1,1,1);
Insert Into C##Server3773.Client values (Null, 'client2@domain.com', 'Client1232', 'ClientP2', 'ClientN2', To_Date('1990/2/1'), '1234567890',2,2,2);
Insert Into C##Server3773.Client values (Null, 'client3@domain.com', 'Client1233', 'ClientP3', 'ClientN3', To_Date('1990/3/1'), '1234567890',3,3,3);
Insert Into C##Server3773.Client values (Null, 'client4@domain.com', 'Client1234', 'ClientP4', 'ClientN4', To_Date('1990/4/1'), '1234567890',1,2,4);
Insert Into C##Server3773.Client values (Null, 'client5@domain.com', 'Client1235', 'ClientP5', 'ClientN5', To_Date('1990/5/1'), '1234567890',2,1,1);

Insert Into C##Server3773.Langue values (Null,'Francais');
Insert Into C##Server3773.Langue values (Null,'Anglais');
Insert Into C##Server3773.Langue values (Null,'Espagnol');
Insert Into C##Server3773.Langue values (Null,'Arabe');
Insert Into C##Server3773.Langue values (Null,'Japonnais');
Insert Into C##Server3773.Langue values (Null,'Russe');

Insert Into C##Server3773.Film values (Null, 'Film1', 1901, 'Resume1', 100, 1);
Insert Into C##Server3773.Film values (Null, 'Film2', 1902, 'Resume2', 100, 2);
Insert Into C##Server3773.Film values (Null, 'Film3', 1903, 'Resume3', 100, 3);
Insert Into C##Server3773.Film values (Null, 'Film4', 1904, 'Resume4', 100, 4);
Insert Into C##Server3773.Film values (Null, 'Film5', 1905, 'Resume5', 100, 5);

Insert Into C##Server3773.Examplaire values (Null,1);
Insert Into C##Server3773.Examplaire values (Null,1);
Insert Into C##Server3773.Examplaire values (Null,2);
Insert Into C##Server3773.Examplaire values (Null,2);
Insert Into C##Server3773.Examplaire values (Null,3);
Insert Into C##Server3773.Examplaire values (Null,3);
Insert Into C##Server3773.Examplaire values (Null,4);
Insert Into C##Server3773.Examplaire values (Null,4);
Insert Into C##Server3773.Examplaire values (Null,5);
Insert Into C##Server3773.Examplaire values (Null,5);

Insert Into C##Server3773.Location values (Null, Sysdate, Sysdate+7,Null,1,1);
Insert Into C##Server3773.Location values (Null, Sysdate, Sysdate+14,Null,2,2);
Insert Into C##Server3773.Location values (Null, Sysdate, Sysdate+14,Null,3,2);
Insert Into C##Server3773.Location values (Null, Sysdate, Sysdate+999,Null,5,3);
Insert Into C##Server3773.Location values (Null, Sysdate, Sysdate+999,Null,7,3);

Insert Into C##Server3773.Acteur values(Null, 'ActP1', 'ActN1', To_Date('1900/1/1'),'ActL1','Bio1');
Insert Into C##Server3773.Acteur values(Null, 'ActP2', 'ActN3', To_Date('1900/2/1'),'ActL2','Bio2');
Insert Into C##Server3773.Acteur values(Null, 'ActP3', 'ActN4', To_Date('1900/3/1'),'ActL3','Bio3');

Insert Into C##Server3773.Personnage values (Null, 'PersP1','PersN1',To_Date('1900/1/1'), 1); 
Insert Into C##Server3773.Personnage values (Null, 'PersP2','PersN2',To_Date('1900/2/1'), 2); 
Insert Into C##Server3773.Personnage values (Null, 'PersP3','PersN3',To_Date('1900/3/1'), 3); 
Insert Into C##Server3773.Personnage values (Null, 'PersP4','PersN4',To_Date('1900/4/1'), 1); 
Insert Into C##Server3773.Personnage values (Null, 'PersP5','PersN5',To_Date('1900/5/1'), 2); 
Insert Into C##Server3773.Personnage values (Null, 'PersP6','PersN6',To_Date('1900/6/1'), 3); 
Insert Into C##Server3773.Personnage values (Null, 'PersP7','PersN7',To_Date('1900/7/1'), 1); 
Insert Into C##Server3773.Personnage values (Null, 'PersP8','PersN8',To_Date('1900/8/1'), 2); 
Insert Into C##Server3773.Personnage values (Null, 'PersP9','PersN9',To_Date('1900/9/1'), 3); 
Insert Into C##Server3773.Personnage values (Null, 'PersP0','PersN0',To_Date('1900/10/1'), 1); 

Insert Into C##Server3773.LienFilmPersonnage values (1,1);
Insert Into C##Server3773.LienFilmPersonnage values (1,2);
Insert Into C##Server3773.LienFilmPersonnage values (2,3);
Insert Into C##Server3773.LienFilmPersonnage values (2,4);
Insert Into C##Server3773.LienFilmPersonnage values (3,5);
Insert Into C##Server3773.LienFilmPersonnage values (3,6);
Insert Into C##Server3773.LienFilmPersonnage values (4,7);
Insert Into C##Server3773.LienFilmPersonnage values (4,8);
Insert Into C##Server3773.LienFilmPersonnage values (5,9);
Insert Into C##Server3773.LienFilmPersonnage values (5,10);

Insert Into C##Server3773.Genre values (Null, 'Action');
Insert Into C##Server3773.Genre values (Null, 'Romance');
Insert Into C##Server3773.Genre values (Null, 'Horreur');
Insert Into C##Server3773.Genre values (Null, 'Comedy');
Insert Into C##Server3773.Genre values (Null, 'Drame');

Insert Into C##Server3773.LienFilmGenre values (1,1);
Insert Into C##Server3773.LienFilmGenre values (1,2);
Insert Into C##Server3773.LienFilmGenre values (2,2);
Insert Into C##Server3773.LienFilmGenre values (2,3);
Insert Into C##Server3773.LienFilmGenre values (3,3);
Insert Into C##Server3773.LienFilmGenre values (3,4);
Insert Into C##Server3773.LienFilmGenre values (4,4);
Insert Into C##Server3773.LienFilmGenre values (4,5);
Insert Into C##Server3773.LienFilmGenre values (5,5);
Insert Into C##Server3773.LienFilmGenre values (5,1);

Insert Into C##Server3773.Pays values (Null, 'Canada');
Insert Into C##Server3773.Pays values (Null, 'France');
Insert Into C##Server3773.Pays values (Null, 'Mongolie');

Insert Into C##Server3773.LienFilmPays values (1,1);
Insert Into C##Server3773.LienFilmPays values (2,2);
Insert Into C##Server3773.LienFilmPays values (3,3);
Insert Into C##Server3773.LienFilmPays values (4,1);
Insert Into C##Server3773.LienFilmPays values (5,2);

Insert Into C##Server3773.RoleTechnique values (Null, 'Realisateur');
Insert Into C##Server3773.RoleTechnique values (Null, 'Scenariste');

Insert Into C##Server3773.PersonnelTechnique values (Null, 'PTP1', 'PTN1', To_Date('1900/1/1'), 1); 
Insert Into C##Server3773.PersonnelTechnique values (Null, 'PTP2', 'PTN2', To_Date('1900/2/1'), 1); 
Insert Into C##Server3773.PersonnelTechnique values (Null, 'PTP3', 'PTN3', To_Date('1900/3/1'), 2); 
Insert Into C##Server3773.PersonnelTechnique values (Null, 'PTP4', 'PTN4', To_Date('1900/4/1'), 2); 
Insert Into C##Server3773.PersonnelTechnique values (Null, 'PTP5', 'PTN5', To_Date('1900/5/1'), 2);

Insert Into C##Server3773.LienFilmPersonnelTechnique values (1,1);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (1,3);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (1,4);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (2,2);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (2,5);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (2,3);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (3,1);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (3,4);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (3,5);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (4,2);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (4,3);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (4,4);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (5,1);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (5,5);
Insert Into C##Server3773.LienFilmPersonnelTechnique values (5,3);


                /**********************/
                /*CONTRAINTES TRIGGERS*/
                /**********************/
 
 
 -- (Carte De Credit) Verification du Numero A l'aide de l'algorithme de Luhn        
Create Or Replace Trigger Trigger_CarteDeCredit_Numero 
Before Insert On C##Server3773.CarteDeCredit
For Each Row
Declare
    SommeDeLuhn number;
    numero_temporaire number;
    Mauvais_Numero_CarteDeCredit EXCEPTION;
    PRAGMA exception_init(Mauvais_Numero_CarteDeCredit, -20123);
Begin
    SommeDeLuhn := 0;
    
    For compteur In 1..Length(:new.Numero)-1
    Loop
        numero_temporaire := To_Number(Substr(:new.numero,Length(:new.Numero)-compteur,1));
        
        If Mod(compteur,2) != 0 Then
            numero_temporaire := numero_temporaire * 2;
            
            If numero_temporaire > 9 Then
                numero_temporaire := Trunc(numero_temporaire / 10) + Mod(numero_temporaire,10);
                End If;
                
        End If;
        
        SommeDeLuhn := SommeDeLuhn + numero_temporaire;
    End Loop;
    
    If 10 - Mod(SommeDeLuhn,10) != To_Number(Substr(:new.Numero,Length(:new.Numero),1)) Then
        raise_application_error(-20123,'Mauvais Numero De Carte De Credit');
    End If;
    
End; 
/

 -- (Carte De Credit) Verification de la Date d'expiration    
Create Or Replace Trigger Trigger_CarteDeCredit_DateExpiration
Before Insert On C##Server3773.CarteDeCredit
For Each Row
Declare
    CarteExpiree EXCEPTION;
    PRAGMA exception_init(CarteExpiree, -20123);
Begin  
    If :new.DateExpiration < Sysdate Then
        raise_application_error(-20123,'La Carte De Credit est Expire');
    End If;
End;
/

-- (Client) Verification de la Date de Naissance     
Create Or Replace Trigger Trigger_Client_DateDeNaissance
Before Insert On C##Server3773.Client
For Each Row
Declare
    TropJeune EXCEPTION;
    PRAGMA exception_init(TropJeune, -20123);
Begin  
    If :new.DateDeNaissance > add_months( trunc(sysdate), -12*18 )  Then
        raise_application_error(-20123,'Vous devez avoir plus de 18 ans pour vous abonner');
    End If;
End;
/

 -- (Location) Verification de la Date de Location      
Create Or Replace Trigger Trigger_Location_DateLocation
Before Insert On C##Server3773.Location
For Each Row
Declare
    MauvaiseDate EXCEPTION;
    PRAGMA exception_init(MauvaiseDate, -20123);
Begin  
    If :new.DateLocation Not Between (Sysdate-1) And (Sysdate+1)  Then
        raise_application_error(-20123,'La date de location est invalide');
    End If;
End;
/