package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private String matricule;
     private Addresse addresse;
     private String email;
     private String motdepasse;
     private String prenom;
     private String nom;
     private Date datedenaissance;
     private BigDecimal telephone;

    public Employe() {
    }

    public Employe(String matricule, Addresse addresse, String email, String motdepasse, String prenom, String nom, Date datedenaissance, BigDecimal telephone) {
       this.matricule = matricule;
       this.addresse = addresse;
       this.email = email;
       this.motdepasse = motdepasse;
       this.prenom = prenom;
       this.nom = nom;
       this.datedenaissance = datedenaissance;
       this.telephone = telephone;
    }
   
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public Addresse getAddresse() {
        return this.addresse;
    }
    
    public void setAddresse(Addresse addresse) {
        this.addresse = addresse;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Date getDatedenaissance() {
        return this.datedenaissance;
    }
    
    public void setDatedenaissance(Date datedenaissance) {
        this.datedenaissance = datedenaissance;
    }
    public BigDecimal getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(BigDecimal telephone) {
        this.telephone = telephone;
    }




}


