package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private BigDecimal idfilm;
     private Langue langue;
     private String titre;
     private BigDecimal anneedesortie;
     private Clob resume;
     private BigDecimal duree;
     private Set payses = new HashSet(0);
     private Set personnages = new HashSet(0);
     private Set personneltechniques = new HashSet(0);
     private Set genres = new HashSet(0);
     private Set examplaires = new HashSet(0);

    public Film() {
    }

	
    public Film(BigDecimal idfilm, String titre, BigDecimal anneedesortie) {
        this.idfilm = idfilm;
        this.titre = titre;
        this.anneedesortie = anneedesortie;
    }
    public Film(BigDecimal idfilm, Langue langue, String titre, BigDecimal anneedesortie, Clob resume, BigDecimal duree, Set payses, Set personnages, Set personneltechniques, Set genres, Set examplaires) {
       this.idfilm = idfilm;
       this.langue = langue;
       this.titre = titre;
       this.anneedesortie = anneedesortie;
       this.resume = resume;
       this.duree = duree;
       this.payses = payses;
       this.personnages = personnages;
       this.personneltechniques = personneltechniques;
       this.genres = genres;
       this.examplaires = examplaires;
    }
   
    public BigDecimal getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(BigDecimal idfilm) {
        this.idfilm = idfilm;
    }
    public Langue getLangue() {
        return this.langue;
    }
    
    public void setLangue(Langue langue) {
        this.langue = langue;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public BigDecimal getAnneedesortie() {
        return this.anneedesortie;
    }
    
    public void setAnneedesortie(BigDecimal anneedesortie) {
        this.anneedesortie = anneedesortie;
    }
    public Clob getResume() {
        return this.resume;
    }
    
    public void setResume(Clob resume) {
        this.resume = resume;
    }
    public BigDecimal getDuree() {
        return this.duree;
    }
    
    public void setDuree(BigDecimal duree) {
        this.duree = duree;
    }
    public Set getPayses() {
        return this.payses;
    }
    
    public void setPayses(Set payses) {
        this.payses = payses;
    }
    public Set getPersonnages() {
        return this.personnages;
    }
    
    public void setPersonnages(Set personnages) {
        this.personnages = personnages;
    }
    public Set getPersonneltechniques() {
        return this.personneltechniques;
    }
    
    public void setPersonneltechniques(Set personneltechniques) {
        this.personneltechniques = personneltechniques;
    }
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    public Set getExamplaires() {
        return this.examplaires;
    }
    
    public void setExamplaires(Set examplaires) {
        this.examplaires = examplaires;
    }


}


