package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private BigDecimal idgenre;
     private String nomgenre;
     private Set films = new HashSet(0);

    public Genre() {
    }

	
    public Genre(BigDecimal idgenre, String nomgenre) {
        this.idgenre = idgenre;
        this.nomgenre = nomgenre;
    }
    public Genre(BigDecimal idgenre, String nomgenre, Set films) {
       this.idgenre = idgenre;
       this.nomgenre = nomgenre;
       this.films = films;
    }
   
    public BigDecimal getIdgenre() {
        return this.idgenre;
    }
    
    public void setIdgenre(BigDecimal idgenre) {
        this.idgenre = idgenre;
    }
    public String getNomgenre() {
        return this.nomgenre;
    }
    
    public void setNomgenre(String nomgenre) {
        this.nomgenre = nomgenre;
    }
    public Set getFilms() {
        return this.films;
    }
    
    public void setFilms(Set films) {
        this.films = films;
    }




}


