package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Langue generated by hbm2java
 */
public class Langue  implements java.io.Serializable {


     private BigDecimal idlangue;
     private String nomlangue;
     private Set films = new HashSet(0);

    public Langue() {
    }

	
    public Langue(BigDecimal idlangue, String nomlangue) {
        this.idlangue = idlangue;
        this.nomlangue = nomlangue;
    }
    public Langue(BigDecimal idlangue, String nomlangue, Set films) {
       this.idlangue = idlangue;
       this.nomlangue = nomlangue;
       this.films = films;
    }
   
    public BigDecimal getIdlangue() {
        return this.idlangue;
    }
    
    public void setIdlangue(BigDecimal idlangue) {
        this.idlangue = idlangue;
    }
    public String getNomlangue() {
        return this.nomlangue;
    }
    
    public void setNomlangue(String nomlangue) {
        this.nomlangue = nomlangue;
    }
    public Set getFilms() {
        return this.films;
    }
    
    public void setFilms(Set films) {
        this.films = films;
    }




}


