package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Roletechnique generated by hbm2java
 */
public class Roletechnique  implements java.io.Serializable {


     private BigDecimal idrole;
     private String nomrole;
     private Set personneltechniques = new HashSet(0);

    public Roletechnique() {
    }

	
    public Roletechnique(BigDecimal idrole, String nomrole) {
        this.idrole = idrole;
        this.nomrole = nomrole;
    }
    public Roletechnique(BigDecimal idrole, String nomrole, Set personneltechniques) {
       this.idrole = idrole;
       this.nomrole = nomrole;
       this.personneltechniques = personneltechniques;
    }
   
    public BigDecimal getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(BigDecimal idrole) {
        this.idrole = idrole;
    }
    public String getNomrole() {
        return this.nomrole;
    }
    
    public void setNomrole(String nomrole) {
        this.nomrole = nomrole;
    }
    public Set getPersonneltechniques() {
        return this.personneltechniques;
    }
    
    public void setPersonneltechniques(Set personneltechniques) {
        this.personneltechniques = personneltechniques;
    }




}


