package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Addresse generated by hbm2java
 */
public class Addresse  implements java.io.Serializable {


     private BigDecimal idaddresse;
     private BigDecimal numerocivic;
     private String rue;
     private String ville;
     private String province;
     private String codepostal;
     private Set employes = new HashSet(0);
     private Set clients = new HashSet(0);

    public Addresse() {
    }

	
    public Addresse(BigDecimal idaddresse, BigDecimal numerocivic, String rue, String ville, String province, String codepostal) {
        this.idaddresse = idaddresse;
        this.numerocivic = numerocivic;
        this.rue = rue;
        this.ville = ville;
        this.province = province;
        this.codepostal = codepostal;
    }
    public Addresse(BigDecimal idaddresse, BigDecimal numerocivic, String rue, String ville, String province, String codepostal, Set employes, Set clients) {
       this.idaddresse = idaddresse;
       this.numerocivic = numerocivic;
       this.rue = rue;
       this.ville = ville;
       this.province = province;
       this.codepostal = codepostal;
       this.employes = employes;
       this.clients = clients;
    }
   
    public BigDecimal getIdaddresse() {
        return this.idaddresse;
    }
    
    public void setIdaddresse(BigDecimal idaddresse) {
        this.idaddresse = idaddresse;
    }
    public BigDecimal getNumerocivic() {
        return this.numerocivic;
    }
    
    public void setNumerocivic(BigDecimal numerocivic) {
        this.numerocivic = numerocivic;
    }
    public String getRue() {
        return this.rue;
    }
    
    public void setRue(String rue) {
        this.rue = rue;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCodepostal() {
        return this.codepostal;
    }
    
    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }
    public Set getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set employes) {
        this.employes = employes;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


