package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private BigDecimal idclient;
     private Forfait forfait;
     private Addresse addresse;
     private Cartedecredit cartedecredit;
     private String email;
     private String motdepasse;
     private String prenom;
     private String nom;
     private Date datedenaissance;
     private BigDecimal telephone;
     private Set locations = new HashSet(0);

    public Client() {
    }

	
    public Client(BigDecimal idclient, Forfait forfait, Addresse addresse, Cartedecredit cartedecredit, String email, String motdepasse, String prenom, String nom, Date datedenaissance, BigDecimal telephone) {
        this.idclient = idclient;
        this.forfait = forfait;
        this.addresse = addresse;
        this.cartedecredit = cartedecredit;
        this.email = email;
        this.motdepasse = motdepasse;
        this.prenom = prenom;
        this.nom = nom;
        this.datedenaissance = datedenaissance;
        this.telephone = telephone;
    }
    public Client(BigDecimal idclient, Forfait forfait, Addresse addresse, Cartedecredit cartedecredit, String email, String motdepasse, String prenom, String nom, Date datedenaissance, BigDecimal telephone, Set locations) {
       this.idclient = idclient;
       this.forfait = forfait;
       this.addresse = addresse;
       this.cartedecredit = cartedecredit;
       this.email = email;
       this.motdepasse = motdepasse;
       this.prenom = prenom;
       this.nom = nom;
       this.datedenaissance = datedenaissance;
       this.telephone = telephone;
       this.locations = locations;
    }
   
    public BigDecimal getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(BigDecimal idclient) {
        this.idclient = idclient;
    }
    public Forfait getForfait() {
        return this.forfait;
    }
    
    public void setForfait(Forfait forfait) {
        this.forfait = forfait;
    }
    public Addresse getAddresse() {
        return this.addresse;
    }
    
    public void setAddresse(Addresse addresse) {
        this.addresse = addresse;
    }
    public Cartedecredit getCartedecredit() {
        return this.cartedecredit;
    }
    
    public void setCartedecredit(Cartedecredit cartedecredit) {
        this.cartedecredit = cartedecredit;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Date getDatedenaissance() {
        return this.datedenaissance;
    }
    
    public void setDatedenaissance(Date datedenaissance) {
        this.datedenaissance = datedenaissance;
    }
    public BigDecimal getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(BigDecimal telephone) {
        this.telephone = telephone;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


