package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Examplaire generated by hbm2java
 */
public class Examplaire  implements java.io.Serializable {


     private BigDecimal idexamplaire;
     private Film film;
     private Set locations = new HashSet(0);

    public Examplaire() {
    }

	
    public Examplaire(BigDecimal idexamplaire, Film film) {
        this.idexamplaire = idexamplaire;
        this.film = film;
    }
    public Examplaire(BigDecimal idexamplaire, Film film, Set locations) {
       this.idexamplaire = idexamplaire;
       this.film = film;
       this.locations = locations;
    }
   
    public BigDecimal getIdexamplaire() {
        return this.idexamplaire;
    }
    
    public void setIdexamplaire(BigDecimal idexamplaire) {
        this.idexamplaire = idexamplaire;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


