package tp3.entity;
// Generated 2021-11-22 12:55:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Typecartedecredit generated by hbm2java
 */
public class Typecartedecredit  implements java.io.Serializable {


     private BigDecimal idtype;
     private String nomtype;
     private Set cartedecredits = new HashSet(0);

    public Typecartedecredit() {
    }

	
    public Typecartedecredit(BigDecimal idtype, String nomtype) {
        this.idtype = idtype;
        this.nomtype = nomtype;
    }
    public Typecartedecredit(BigDecimal idtype, String nomtype, Set cartedecredits) {
       this.idtype = idtype;
       this.nomtype = nomtype;
       this.cartedecredits = cartedecredits;
    }
   
    public BigDecimal getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(BigDecimal idtype) {
        this.idtype = idtype;
    }
    public String getNomtype() {
        return this.nomtype;
    }
    
    public void setNomtype(String nomtype) {
        this.nomtype = nomtype;
    }
    public Set getCartedecredits() {
        return this.cartedecredits;
    }
    
    public void setCartedecredits(Set cartedecredits) {
        this.cartedecredits = cartedecredits;
    }




}


